name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make zip
      run: make zip

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: selinux_enforce-*.zip
